### ISSUE TITLE
Official Beta release. 

### ISSUE THREAD

**Issue by MasterOfTheTiger** [heb12/heb12-mobile#1]
Maybe you should finish up a couple of things and we can make an official bet 0.1.0 release. :-) 

By thw way here is a bit more about matrix. It is a chat protocol that different apps use. Riot is the most popular of them. It is a chat app like Discord,Skype etc. https://riot.im/app my account is @mott:matrix.org

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz

**Comment by petabyt** [comment]
Ok. I was thinking about finishing up the search function. I might finish the settings page another time.

**Comment by MasterOfTheTiger** [comment]
Whoops it's @ mott:matrix.org (without the space).it's case sensitive.

**Comment by petabyt** [comment]
You may want to delete https://github.com/heb12/Heb12Mobile
and archive https://github.com/heb12/heb12-android/

**Comment by MasterOfTheTiger** [comment]
Will do.
