### ISSUE TITLE
[SECURITY] Debug build submitted as release v0.1.0 

### ISSUE THREAD

**Issue by ed6767** [heb12/heb12-mobile#10]
Release v0.1.0's APK is signed in **debug mode**. This leaves it vulnerable to security issues and therefore I cannot publish the app on the Google Play Store until it has been signed in **production** mode.
----
https://developer.android.com/studio/publish/preparing.html#publishing-configure

**Comment by petabyt** [comment]
Would it be safe to send the APK through Github?

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz A new APK needs to be built which is signed without debug mode or something like that. Can you handle this?

**Comment by petabyt** [comment]
I've been sending @ed6767 some emails with APK's.
