### ISSUE TITLE
app got lag after change something

### ISSUE THREAD

**Issue by muhammadarif1** [heb12/heb12-mobile#12]
**Describe the bug**
after change something in the app it always show 
```javascript error on line 0: script error```
**To Reproduce**
1. open the app
2. search something and bookmark than change translation .'
3. See error

**Expected behavior**
after change some default thing this app will work as welll

**Screenshots**
[https://www.youtube.com/watch?v=v5o0uAjpUJM](url)

*

**Smartphone (please complete the following information):**
 - Device:oppo neo 5
 - OS: [android6.1]

**Additional context**

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz I have noticed this as well.

**Comment by petabyt** [comment]
I'm pretty sure this is an issue with the compatibility. Older Android versions don't support newer Html5 features.

**Comment by muhammadarif1** [comment]
This app support from android 5.0 and my android is 6.0,

**Comment by petabyt** [comment]
Where did it say that? I'm pretty sure the app works on 7.0 and later.

**Comment by muhammadarif1** [comment]
Any Android device running Android 5.0 and later should be able to run Heb12 Mobile. I read it from readme file

**Comment by petabyt** [comment]
Oh. Sorry, that must be old. I'll change it. I did make a version of Heb12 Mobile for older devices here https://github.com/pufflegamerz/Heb12MobileAi2. It's pretty limited though.

**Comment by muhammadarif1** [comment]
Are this a bug or not?

**Comment by petabyt** [comment]
No, this is not a bug. Your device is not supported. I'm working on finding a way to support older devices though.

**Comment by muhammadarif1** [comment]
You can close the issue if this not a bug

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz His device is 6.0 right? Then it should certainly be supported. You can't say it supports older versions of Android but not have it work.... 

I use Android 5.0 as well. So what needs to be changed to get it working?

**Comment by petabyt** [comment]
@MasterOfTheTiger Does the app work on your device?

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz Generally yes, but I ran into some small errors which are similar to what this user is experiencing.

**Comment by petabyt** [comment]
I'm going to see if I can figure out what the errors are.

**Comment by muhammadarif1** [comment]
Let me know when you verify that errors

**Comment by pufflegamerz** [comment]
Try this APK. I replaced some functions with alternatives that most devices will support.
[app-debug.zip](https://github.com/heb12/heb12-mobile/files/3221015/app-debug.zip)

**Comment by petabyt** [comment]
Try this APK. I replaced some functions with something that should work on more devices.
[app.zip](https://github.com/heb12/heb12-mobile/files/3221063/app.zip)

**Comment by muhammadarif1** [comment]
I am a bug hunter,  let me know when you verify this error

**Comment by petabyt** [comment]
Does the APK in the ZIP file work?

**Comment by muhammadarif1** [comment]
This app freeze 
```ANR in com.heb12.heb12 (com.heb12.heb12/.MainActivity), time=43530507
Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 11.  Wait queue head age: 8660.7ms.), happend at time = 43530504@#@29504
Load: 10.89 / 10.7 / 10.51
Android time :[2019-05-27 04:42:38.42] [43538,371]
CPU usage from 10471ms to 2037ms ago:
  192% 29504/com.heb12.heb12: 177% user + 15% kernel / faults: 29485 minor 1 major
    98% 29545/Chrome_InProcRe: 93% user + 4.7% kernel
    67% 29504/com.heb12.heb12: 62% user + 4.8% kernel
    4.6% 29522/GCDaemon: 4.3% user + 0.2% kernel
    3.4% 29557/RenderThread: 2.3% user + 1% kernel
    3.2% 29553/Chrome_ChildIOT: 2.2% user + 0.9% kernel
    2.8% 29535/Chrome_IOThread: 1.5% user + 1.3% kernel
    2.2% 29537/TaskSchedulerFo: 2.1% user + 0.1% kernel
    2.2% 29546/Chrome_InProcGp: 1.7% user + 0.4% kernel
    2% 29558/Compositor: 2% user + 0% kernel
    1.3% 29559/CompositorTileW: 1.3% user + 0% kernel
    0.5% 29519/FinalizerDaemon: 0.5% user + 0% kernel
    0.4% 29524/Binder_2: 0.2% user + 0.2% kernel
    0.4% 29532/TaskSchedulerFo: 0.4% user + 0% kernel
    0.4% 29562/TaskSchedulerFo: 0.4% user + 0% kernel
    0.3% 29523/Binder_1: 0.1% user + 0.2% kernel
    0.3% 29549/arch_worker: 0.3% user + 0% kernel
    0.3% 29565/Binder_3: 0.1% user + 0.2% kernel
    0.2% 29518/ReferenceQueueD: 0.2% user + 0% kernel
    0.2% 29548/Chrome_ChildIOT: 0.2% user + 0% kernel
    0.2% 29551/SWD-GPU Job: 0% user + 0.2% kernel
    0.2% 29552/SWD-Frame: 0% user + 0.2% kernel
   +0% 29580/FileObserver: 0% user + 0% kernel
   +0% 29586/Binder_4: 0% user + 0% kernel
  38% 900/system_server: 27% user + 11% kernel / faults: 1986 minor 1 major
    4.9% 914/GCDaemon: 4.5% user + 0.4% kernel
    2.8% 952/android.display: 1.4% user + 1.4% kernel
    2.6% 939/ActivityManager: 0.8% user + 1.7% kernel
    2.2% 2328/Binder_10: 1.8% user + 0.3% kernel
    2% 2004/Binder_6: 1.6% user + 0.3% kernel
    1.8% 1473/InputDispatcher: 1.1% user + 0.7% kernel
    1.5% 2300/Binder_D: 1% user + 0.4% kernel
    1.4% 916/Binder_1: 0.8% user + 0.5% kernel
    1.4% 917/Binder_2: 1% user + 0.3% kernel
    1.4% 2002/Binder_5: 1% user + 0.3% kernel
    1.4% 2243/Binder_9: 0.8% user + 0.5% kernel
    1.4% 2280/Binder_B: 1.3% user + 0.1% kernel
    1.3% 2117/Binder_7: 0.9% user + 0.3% kernel
    1.1% 2304/Binder_F: 1% user + 0.1% kernel
    1% 959/Binder_3: 0.9% user + 0.1% kernel
    1% 1561/Binder_4: 0.7% user + 0.3% kernel
    1% 2242/Binder_8: 0.5% user + 0.4% kernel
    1% 2298/Binder_C: 0.8% user + 0.2% kernel
    1% 2303/Binder_E: 0.9% user + 0.1% kernel
    0.8% 900/system_server: 0.2% user + 0.5% kernel
    0.7% 950/android.ui: 0.5% user + 0.1% kernel
    0.5% 967/AnrMonitorThrea: 0% user + 0.5% kernel
    0.5% 1474/InputReader: 0.4% user + 0.1% kernel
    0.4% 1485/NetworkPolicy: 0.2% user + 0.2% kernel
    0.4% 1493/ConnectivitySer: 0.4% user + 0% kernel
    0.3% 911/FinalizerDaemon: 0.1% user + 0.2% kernel
    0.2% 1496/OppoExService: 0.1% user + 0.1% kernel
    0.1% 910/ReferenceQueueD: 0.1% user + 0% kernel
    0.1% 953/ProcessManagerT: 0.1% user + 0% kernel
    0.1% 1555/LazyTaskWriterT: 0% user + 0.1% kernel
  8.1% 1704/com.android.systemui: 5.9% user + 2.2% kernel / faults: 2318 minor 1 major
    5.9% 1704/ndroid.systemui: 4.7% user + 1.1% kernel
    0.5% 2157/RenderThread: 0.4% user + 0.1% kernel
    0.2% 6263/Binder_7: 0.2% user + 0% kernel
    0.1% 2350/Timer-0: 0% user + 0.1% kernel
    0.1% 2825/Binder_3: 0% user + 0.1% kernel
    0.1% 6264/Binder_8: 0% user + 0.1% kernel
    0.1% 13713/Binder_A: 0% user + 0.1% kernel
    0.1% 14389/Binder_5: 0% user + 0.1% kernel
    0.1% 15053/Binder_D: 0% user + 0.1% kernel
    0.1% 17288/Binder_E: 0% user + 0.1% kernel
    0.1% 20267/Binder_B: 0.1% user + 0% kernel
    0.1% 21989/Binder_10: 0% user + 0.1% kernel
    0.1% 24743/Binder_6: 0.1% user + 0% kernel
    0.1% 28098/Binder_C: 0% user + 0.1% kernel
  4.8% 169/surfa```

**Comment by muhammadarif1** [comment]
This app freez after change something also

**Comment by petabyt** [comment]
What did you do to cause the crash?

**Comment by muhammadarif1** [comment]
Change surah

**Comment by petabyt** [comment]
What is a surah?

**Comment by muhammadarif1** [comment]
![Screenshot_2019-05-27-09-24-35-26](https://user-images.githubusercontent.com/36690337/58391841-8e5aa900-8061-11e9-82c2-cec3b16cd0bf.png)

**Comment by petabyt** [comment]
Hmmm. Micah seems to be working fine on Android 6.0 for me.

**Comment by muhammadarif1** [comment]
Change to another

**Comment by petabyt** [comment]
Another what?

**Comment by MasterOfTheTiger** [comment]
There's a lot of unpredictable bugs in the switcher.

**Comment by petabyt** [comment]
I'll investigate tomorrow. Here's a list of bugs that came up while I was changing everything.

- Bookmarking doesn't work on kindle

**Comment by MasterOfTheTiger** [comment]
The NET problems could be resolved easier by looking at Heb12 Desktop's code. It supports all that.

**Comment by MasterOfTheTiger** [comment]
Just doing some housekeeping. Is this issue still relevant?

**Comment by petabyt** [comment]
I think this is fixed, but there are still some similar issues I need to fix.
