### ISSUE TITLE
Simplify Release Process

### ISSUE THREAD

**Issue by MasterOfTheTiger** [heb12/heb12-mobile#13]
We need to revise the whole system to make it easier for releasing. We need to standardize the process and avoid problems. The release of v0.1.0 showed just how 

Things which need to be done:
- [ ] A single, signed APK for all platforms
- [ ] **Make sure signatures are the same, and take care of them responsibly**
- More to be added

Here are everyone's roles:

@pufflegamerz is the head of Heb12 Mobile and the one in charge of releases and the Amazon app store publishing.

@ed6767 is responsible for publishing to the Google Play Store

@MasterOfTheTiger will oversee it all and hopefully manage the F-Droid release. 

This issue cannot be closed until we come up with a clear, documented solution for these problems.

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz As we are going to probably release soon, we should make sure that we have everything figured out. Have you got the signed APKs all sorted out?

**Comment by petabyt** [comment]
@MasterOfTheTiger Sorry, I didn't see this until now. One of the issues with the last release is that they were released at different times, so each apk had different changes. 

This time I will have all the files ready, then start working on releasing them to stores, one at a time. It might even be better if I have a release branch.

**Comment by MasterOfTheTiger** [comment]
Just tag the repo at v0.2.0 when it is ready, then build all the APKs off of that.
