### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by rugk** [heb12/heb12-mobile#14]
Please release it on F-Droid and add an F-Droid badge on the website.

---

[F-Droid](https://f-droid.org/) is an Android app store specifically for free/libre open-source apps. It would be great if your app could be released there, as it is the number one for getting FLOSS Android apps for many people.
F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/)), so downloads from there can be trusted.

The [app developer FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/) or [the quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) may help you to get started.

---

I saw https://github.com/heb12/heb12-mobile/issues/13, but I thought possibly a separate issue for that may be better suited.

**Comment by petabyt** [comment]
I was thinking @MasterOfTheTiger would do that.

**Comment by rugk** [comment]
remove the space after the add to mention @MasterOfTheTiger

**Comment by MasterOfTheTiger** [comment]
I have been reading the docs (even before this issue) to see what it would require to get it on F-Droid. :-)

**Comment by petabyt** [comment]
@MasterOfTheTiger I'm pretty sure the F-Droid requirements match up with the app. I can upload the app if this week.

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz I am going to start it myself first. Do you mind? I am going to start now.

**Comment by MasterOfTheTiger** [comment]
Well, if you can do it, that would be great. I may not be able to at the moment.

**Comment by petabyt** [comment]
I've submitted it https://gitlab.com/fdroid/rfp/issues/1040

**Comment by hotlittlewhitedog** [comment]
@pufflegamerz please react on your Fdroid RFP.

**Comment by Poussinou** [comment]
Your app is now available [here](https://f-droid.org/packages/com.heb12.heb12/). you can add a badge in your readme with this image: https://fdroid.gitlab.io/artwork/badge/get-it-on.png

**Comment by MasterOfTheTiger** [comment]
Thanks everyone for your efforts. This issue has now been resolved and the banner is in the README.
