### ISSUE TITLE
Add Downloadable Translations

### ISSUE THREAD

**Issue by petabyt** [heb12/heb12-mobile#15]
I would like to get started with the downloadable translation feature. I am thinking about just getting the files from https://gitlab.com/MasterOfTheTiger/openbibles but @MasterOfTheTiger if you want to create an API that would be better.

**Comment by MasterOfTheTiger** [comment]
We also need an API endpoint where the application can ask what versions are available.

**Comment by petabyt** [comment]
I am making it so that when the user downloads a translation, it will be put in a folder called "translations"
