### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by petabyt** [heb12/heb12-mobile#16]
This next release will have the downloadable translations that I added earlier. I will also fix the existing bugs and try to improve the app's performance a little bit.

**Comment by MasterOfTheTiger** [comment]
Does that mean that I need to prioritize work on some kind of API? Because that will take a while. I would just advise you revising your tools to work directly with gratis.bible.

**Comment by petabyt** [comment]
I use this thing I forked: https://github.com/pufflegamerz/openbibles. I'm not saying I'm working on releasing it right now, but I'm just writing down my plans. Also, what is gratis.bible? Is it an API? Heb12 Mobile would have to use an API that supports JSONP.

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz gratis.bible is where I got all of the existing openbibles text. I made a couple modifications to our version, but if you modify your processing code, you can use it directly from there.

I may want to depreciate the current openbibles in the future, and instead use gratis.bible and sword modules. That reminds me, you may want to consider implementing the Sword library into Heb12 Mobile. It will allow for *many* translations.

**Comment by petabyt** [comment]
I also have another problem, when you download more than 5 translations, the app won't start (probably crashes). I'm gonna have to fix that first.

**Comment by petabyt** [comment]
@MasterOfTheTiger Did you get the text from this repo: https://github.com/gratis-bible/bible and convert it to JSON?

**Comment by MasterOfTheTiger** [comment]
Yes. That is exactly what I did. I also made a couple other changes which I later found was not necessary.

**Comment by MasterOfTheTiger** [comment]
How is the next release coming along? You have made enough changes that I think a v0.2.0 is a good idea. What do you think?

**Comment by petabyt** [comment]
@MasterOfTheTiger I was hoping to release it soon. After some more testing, I think it will be ready.

**Comment by MasterOfTheTiger** [comment]
So does it support downloading more translations from your server? And does it come with any translations by default?

Also, in an old version at least, it randomly resets to Genesis 1 upon restart, but only the text, not the drop down.

In addition, after this, let's move to a more rapid release cycle.

**Comment by petabyt** [comment]
I removed 2 of the translations, so the whole app was based off of Openbibles.
I'll upload a recent apk for you to test out.

**Comment by petabyt** [comment]
Here: https://github.com/heb12/heb12-mobile/releases/tag/0.1.1

**Comment by petabyt** [comment]
@MasterOfTheTiger  Is code.theres.life down? I can't access theres.life either.

**Comment by MasterOfTheTiger** [comment]
I am so sorry. There has been some issues and both servers went down. I will have this fixed ASAP.

**Comment by petabyt** [comment]
It isn't that big of a deal. I assumed I would see something on about.theres.life.

**Comment by MasterOfTheTiger** [comment]
Okay. Let's come up with a schedule. Also, I think it should be 0.2.0 because of the amount of features added.

I think we should aim for January 31st at the latest. Thus making it:
Feature freeze:
January 15th - stop working on any new features after this
Then it can be extensively tested for bugs and fixed until the 31st, when we release. During that time we must also make sure everyone involved is ready for a release (read: @ed6767).

**Comment by petabyt** [comment]
@MasterOfTheTiger Sounds good

**Comment by MasterOfTheTiger** [comment]
Here is a draft of the release notes (a final version will have to be written upon the real release, but this gives us an idea of what has been done so far):

### Added
- Downloadable translations
- Finished Spanish translation
- German translation (childofgod@theres.life)
- Custom search engines
- Custom highlighting colors

### Changed
- Config file layout

### Fixed
- Bookmarking
- Other crashes and misc bugs

**Comment by petabyt** [comment]
Will changing the location of the translation and configuration files count as adding a feature? I have a ton of tests and crap this week (including the FitnessGram Pacer Test) so I probably won't be able to work on it.
Should it go in release v0.3.0? It's not a huge deal, it won't have any effect on the user.

**Comment by MasterOfTheTiger** [comment]
This is an important change and should make the v0.2.0 release. These are just guidelines anyway, not bindling laws. (but no, I would not categorize it as a "feature" strictly anyway)

**Comment by petabyt** [comment]
Ok. I guess I need to write some Java to do that, then fix some more configuration file bugs, and an issue with the welcome message.
