### ISSUE TITLE
Can't return translation string larger than 15MB 

### ISSUE THREAD

**Issue by petabyt** [heb12/heb12-mobile#17]
**Describe the bug**
When the app starts, it requests to get every translation in 1 string. This can be very big (30mb). For some reason, the app crashes and won't load. I get error: Uncaught Error: Java exception was raised during method invocation
**To Reproduce**
1. Download more than 3 translations
2. See error

**Expected behavior**
The app should load fine

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Android 7.0]

**Smartphone (please complete the following information):**
 - Device: [LG VS501]

**Comment by MasterOfTheTiger** [comment]
This seems like we need to have it only request a translation when the user selects it, and replaced when a new one is selected. It can load it fairly quickly anyway right?

**Comment by petabyt** [comment]
Oh yeah. I have no idea why I didn't think of that. I'll try it later.

**Comment by MasterOfTheTiger** [comment]
Can you link to the commit in which this was fixed?

**Comment by petabyt** [comment]
@MasterOfTheTiger I'm pretty sure it is this: https://github.com/heb12/heb12-mobile/commit/bc6c2bd9992a58074fe84c8f90d6e65e268ecb97
