### ISSUE TITLE
Decluttering the Sidebar

### ISSUE THREAD

**Issue by petabyt** [heb12/heb12-mobile#18]
The sidebar has a bunch of stuff, and a lot of it is unnecessary. I've made a test image for how it could look
![Capture+_2019-08-17-23-01-10](https://user-images.githubusercontent.com/32369330/63219615-36e94800-c13b-11e9-8fad-35281b39079a.png)
I like the idea of sticking the VOTD to the bottom, but the stuff on the top looks a little weird. Any ideas?

**Comment by MasterOfTheTiger** [comment]
Maybe make a new translation switcher, and put it next to the chapter switcher. Instead of using a `<select>` box, you may want to actually make a better popup menu for it.

**Comment by petabyt** [comment]
This is a pretty big issue since there is so much text that the sidebar animation lags some. I have made a Google Drawing with some better ideas https://docs.google.com/drawings/d/1B5WcMrP_BaHlAwgMtwTJX0C5Lmn13orCJCddCOVkBDQ/edit?usp=sharing

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz Can you include the file here? I can't see the drawing through Google drawings.

**Comment by petabyt** [comment]
![Screenshot (481)](https://user-images.githubusercontent.com/32369330/63376985-a8e8a980-c354-11e9-9c8c-39f2b7eebd80.png)

**Comment by MasterOfTheTiger** [comment]
It looks better, but the "Change translation" button isn't very useful as it doesn't show any info by itself. Honestly I'd even prefer the current translation select menu over this button.

**Comment by petabyt** [comment]
Here is an updated image
![Screenshot (483)](https://user-images.githubusercontent.com/32369330/63466826-b6bc2e80-c429-11e9-8147-636058673221.png)
I'm not sure if It would be all that necessary to make popup for selecting translations. It also couldn't make a description for every translation, since there are about 40+ of them on my server.

**Comment by MasterOfTheTiger** [comment]
Well we'll just have to improve the API then. But do not worry about that now. I'll work on it when I have time to work on my rebuilding of Heb12 desktop again.

**Comment by petabyt** [comment]
Didn't you mention you were rewriting it in Python or something? Also, I'm working on a side project, Heb12DOS (Heb12 for MS-DOS)

**Comment by MasterOfTheTiger** [comment]
Yep. That's what I am doing.
