### ISSUE TITLE
[Feature request] Custom Highlight Colors

### ISSUE THREAD

**Issue by MasterOfTheTiger** [heb12/heb12-mobile#19]
I believe it would be a good idea to allow for custom colors im the highlight menu. That way anyone can add any color they want.

It should probably use a color picker, but earlier versions could use use HTML code as input.

We shouldn't throw in unecessary dependancies though.

**Comment by petabyt** [comment]
I definitely think this is something I should do when I improve the configuration file setup.

**Comment by MasterOfTheTiger** [comment]
Is this still planned?

**Comment by petabyt** [comment]
@MasterOfTheTiger Yes. I hope to add it before the next release. It shouldn't be too hard.

**Comment by MasterOfTheTiger** [comment]
For it to be useful generally, you would also have to have some kind of picker. But I don't think that is entirely necessary at the moment.

**Comment by petabyt** [comment]
@MasterOfTheTiger I wonder if the HTML color picker will work here.

**Comment by petabyt** [comment]
The HTML color input does work. It's not the best, but I think it will do.
![Capture+_2020-01-05-13-46-41](https://user-images.githubusercontent.com/32369330/71784495-0c047100-2fc2-11ea-8c55-df405c97161c.png)
