### ISSUE TITLE
Allow different search engines to be used

### ISSUE THREAD

**Issue by zachdecook** [heb12/heb12-mobile#20]
Not just google.nl

**Comment by MasterOfTheTiger** [comment]
I forgot about this. 

@pufflegamerz If you can, please enable some kind of changing search options, or put it on BibleHub or something like that. Eventually I hope for us to have our own Heb12 website with a web app you could link to until then we need to improve the existing search feature..

**Comment by petabyt** [comment]
I guess I can create an option for Google/DuckDuckGo/etc.

**Comment by petabyt** [comment]
Fixed in https://github.com/heb12/heb12-mobile/commit/7728247c1bd4c703c88638392810a975a8f0a1ee
