### ISSUE TITLE
Redesign CSS

### ISSUE THREAD

**Issue by MasterOfTheTiger** [heb12/heb12-mobile#23]
I think the whole app needs a redesign to make it look more "fresh" and modern. I was thinking that we could maybe implement some of the CSS I designed for Heb12 Desktop into Heb12 Mobile since I specifically wanted it to be scalable. Specifically I would prefer simpler and less spacious arrow buttons, and a cleaner color scheme (white with shadows works). Ignore me if you want, but I really liked the design for Heb12 Desktop in these ways.

**Comment by MasterOfTheTiger** [comment]
Note: if you give this a go, I will work on it.

**Comment by petabyt** [comment]
I always loved the main UI style, I never thought of changing it.

**Comment by MasterOfTheTiger** [comment]
Okay. That's fine. I'd still like to give it a go to see how you like it. No pressure to merge though.

**Comment by petabyt** [comment]
You can always add a different theme though.

**Comment by MasterOfTheTiger** [comment]
Let me do a couple changes in another branch and you can say what you think. Mostly I find the "previous" and "next" buttons too spacious (since arrow buttons don't need to take a whole row at the bottom of the screen).
