### ISSUE TITLE
Clarify GPL

### ISSUE THREAD

**Issue by MasterOfTheTiger** [heb12/heb12-mobile#25]
Clarify the license by stating that this software is licensed under the GPL version 3 or later in the README. Also, the F-Droid metadata needs to be changed for "3 or later" as well. 

It would be best to put a license notice in all main source files (as mentioned in the GPL text), but the README itself is vital.

**Comment by petabyt** [comment]
I can easily put a license notice on the README, but I think putting in the source code files is a bit excessive.
