### ISSUE TITLE
Combine Highlighting Menu and Verse Popup

### ISSUE THREAD

**Issue by petabyt** [heb12/heb12-mobile#5]
The menu popup and the highlighting verse are both a little confusing. I'm not sure how good they will look combined, but I think it might be a good idea.

**Comment by MasterOfTheTiger** [comment]
Do it more like YouVersion's.

**Comment by petabyt** [comment]
I made a couple of changes. It's still a little hard to tap on the little number, but having everything in 1 popup is very convenient.

**Comment by MasterOfTheTiger** [comment]
How about you simply tap on the verse like you had before. But do that for everything.

**Comment by MasterOfTheTiger** [comment]
Awesome! Can you add a new apk? I want to see your progress. :-)

**Comment by petabyt** [comment]
I'm working on adding font sizes, so I'll build it once I'm done.
