### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by MasterOfTheTiger** [heb12/heb12-mobile#7]
Here is the timeline (you are the developer so you can change accordingly). 

Feature freeze: March 30
UI freeze: April 15 
Release: May 1 

How does this sound? We stop working on features for v0.1.0 and accepting pull request features by the end of March. We do not change the UI after April 15. And we release May 1. Does that sound good?

**Comment by petabyt** [comment]
Ok. I was thinking about releasing a little earlier, but this will do.

**Comment by petabyt** [comment]
I just realized that you set the release of the app a day before its 1 year anniversary.

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz Oh wow. I knew it was close. Well, we are close to feature freeze. Is March 30th still good for that or do we need it post-poned?

**Comment by petabyt** [comment]
Is there anything else that I should add? I was thinking about adding bookmarks.

**Comment by petabyt** [comment]
Should I add support for Spanish?

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz Yes, you should add bookmarks. In addition, adding support for other languages is a *huge* step which should be done early (I am working on getting Heb12 Desktop to support French at the moment, and it is a lot of work).

**Comment by petabyt** [comment]
Added bookmarks. Sorry about the huge screenshots.
![Capture+_2019-03-30-14-13-45](https://user-images.githubusercontent.com/32369330/55280004-be99fb80-52ed-11e9-9feb-c63e16211718.png)
![Capture+_2019-03-30-14-13-34](https://user-images.githubusercontent.com/32369330/55280005-be99fb80-52ed-11e9-8f21-db46de4ab11c.png)

**Comment by petabyt** [comment]
Could we release the app a little early if we don't get any pull requests?

**Comment by MasterOfTheTiger** [comment]
Okay. I really want to help work with it. But that might not happen soon enough. There's a lot of work which needs to be done. But I think it looks good so far for the first version.

**Comment by petabyt** [comment]
What should we add?

**Comment by MasterOfTheTiger** [comment]
For one, soon I will build an openbibles API for both retrieving and downloading Bible translations. That will take a lot of work to implement, but it would surely be very useful.

**Comment by petabyt** [comment]
Also, I've been trying to install a good Linux distro on my laptop. Any recommendations? I've already tried Ubuntu and Fedora.

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz Honestly here is not the best place to talk about it (since it's an issue tracker), but I recommend Antergos maybe.

Maybe contact me a different way (maybe theres.life since you are on that) for more info on that sort of thing.

**Comment by MasterOfTheTiger** [comment]
How far now?

**Comment by MasterOfTheTiger** [comment]
I have a development version set up, but I can't run it in the emulator or on my tablet, even when installing all the right SDKs. It just won't show up.

**Comment by petabyt** [comment]
The html file won't show up? Or is the app not installing?

**Comment by petabyt** [comment]
I've been really busy with schoolwork so I haven't been able to work on it a lot. I'll try to work on it a little today and see if I can help with the issue.

**Comment by MasterOfTheTiger** [comment]
The run button doesn't work. I had to just build the apk and manually move it over and install it for every change. I also have made progress on the translation bug.

**Comment by petabyt** [comment]
I don't use the run button. I preview the html files in my browser
build the apk and send it to my device when I want to test the actual
app.

**Comment by petabyt** [comment]
I think I just fixed the translation issue.

**Comment by petabyt** [comment]
When are we planning on releasing the app?

**Comment by MasterOfTheTiger** [comment]
> I don't use the run button. I preview the html files in my browser
build the apk and send it to my device when I want to test the actual
app.

Okay. Good to know. 

> I think I just fixed the translation issue.

I will check it out. I also made a few changes you might want to merge if you feel like it.

**Comment by petabyt** [comment]
Sorry about my inactivity, I have been really busy lately. Do you think I should release the app to the Amazon Appstore?

**Comment by MasterOfTheTiger** [comment]
Let's do one more extensive test of everything, and then tag and release 0.1.0. And delete the pre-release folder before tagging it.

**Comment by petabyt** [comment]
Do you know of any bugs currently in the app? I think it might be good to go.

**Comment by MasterOfTheTiger** [comment]
Go ahead. If you think it's good, do this: 
1. Remove the pre-release folder 
2. Tag the repo for v0.1.0 
3. Add release description and upload the APK file as something like `Heb12-0.1.0.apk` 
4. Work on publishing

**Comment by MasterOfTheTiger** [comment]
With any bugs, we will just fix them in 0.1.1

**Comment by petabyt** [comment]
Just submitted it to the Amazon Appstore. Should be up tomorrow.

**Comment by MasterOfTheTiger** [comment]
Awesome! Thanks so much for this. I'll be on the lookout. Meanwhile, I have someone to put it on Google Play as well.

**Comment by MasterOfTheTiger** [comment]
Awesome! Thanks so much for this. I'll be on the lookout. Meanwhile, I have someone to put it on Google Play as well.

**Comment by MasterOfTheTiger** [comment]
Make sure the listed name is "Heb12 Bible" or something like that, so people know instantly what it is

**Comment by MasterOfTheTiger** [comment]
I'll close this issue once it is fully available in the Amazon app store, and Google Play

**Comment by petabyt** [comment]
Also, we need a way to download translations within the app. I think we should make some kind of special API or something.

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz Yes, I am working on this very thing for Heb12 Desktop v0.4.0. Someone has given me server space to do it as well. We can implement it into Heb12 Mobile v0.2.0 after Heb12 Desktop v0.4.0 is completed.

**Comment by MasterOfTheTiger** [comment]
It's in the Play store! https://play.google.com/store/apps/details?id=com.heb12.heb12
